const app = document.querySelector('#app'), nav = document.querySelector('#editor-nav'), status = document.querySelector('#storage-status');
const manifestPath = app.dataset.manifest, homeTemplate = document.querySelector('#home-template');
const state = { manifest: null, files: new Map(), localRoot: null, activePath: null, glyph: 0, color: 1, selector: 1 };
let PALETTE = [];
const text = new TextEncoder(), decode = new TextDecoder(), $ = (s, r = document) => r.querySelector(s);
const el = (tag, attrs = {}, children = []) => { const n = document.createElement(tag); Object.entries(attrs).forEach(([k, v]) => k === 'class' ? n.className = v : k.startsWith('on') ? n.addEventListener(k.slice(2), v) : n.setAttribute(k, v)); children.flat().forEach(c => n.append(c instanceof Node ? c : document.createTextNode(c))); return n; };
const concat = parts => { const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0)); let at = 0; parts.forEach(p => { out.set(p, at); at += p.length; }); return out; };
async function inflate(bytes) { return new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate'))).arrayBuffer()); }
async function deflate(bytes) { return new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('deflate'))).arrayBuffer()); }
function crc32(bytes) { let crc = -1; for (const value of bytes) { crc ^= value; for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0); } return (crc ^ -1) >>> 0; }
function chunk(type, body) { const out = new Uint8Array(body.length + 12), view = new DataView(out.buffer); view.setUint32(0, body.length); out.set(text.encode(type), 4); out.set(body, 8); view.setUint32(body.length + 8, crc32(out.slice(4, body.length + 8))); return out; }
async function decodePng(buffer) { const data = new Uint8Array(buffer); if (data.length < 8 || data[0] !== 137 || data[1] !== 80 || data[2] !== 78 || data[3] !== 71 || data[4] !== 13 || data[5] !== 10 || data[6] !== 26 || data[7] !== 10) throw new Error('Expected indexed PNG'); let width, height, palette, chunks = [], at = 8; while (at < data.length) { const length = new DataView(data.buffer, data.byteOffset + at).getUint32(0), type = decode.decode(data.slice(at + 4, at + 8)), body = data.slice(at + 8, at + 8 + length); at += length + 12; if (type === 'IHDR') { const v = new DataView(body.buffer, body.byteOffset); width = v.getUint32(0); height = v.getUint32(4); if (body[8] !== 8 || body[9] !== 3 || body[12] !== 0) throw new Error('Expected non-interlaced indexed PNG'); } if (type === 'PLTE') palette = Array.from({ length: body.length / 3 }, (_, i) => `#${[body[i * 3], body[i * 3 + 1], body[i * 3 + 2]].map(x => x.toString(16).padStart(2, '0')).join('')}`); if (type === 'IDAT') chunks.push(body); if (type === 'IEND') break; }
  const raw = await inflate(concat(chunks)), pixels = new Uint8Array(width * height); let previous = new Uint8Array(width); at = 0; for (let y = 0; y < height; y++) { const filter = raw[at++], encoded = raw.slice(at, at += width), row = new Uint8Array(width); for (let x = 0; x < width; x++) { const l = x ? row[x - 1] : 0, u = previous[x], ul = x ? previous[x - 1] : 0; if (filter === 0) row[x] = encoded[x]; else if (filter === 1) row[x] = (encoded[x] + l) & 255; else if (filter === 2) row[x] = (encoded[x] + u) & 255; else if (filter === 3) row[x] = (encoded[x] + Math.floor((l + u) / 2)) & 255; else if (filter === 4) { const p = l + u - ul, a = Math.abs(p - l), b = Math.abs(p - u), c = Math.abs(p - ul); row[x] = (encoded[x] + (a <= b && a <= c ? l : b <= c ? u : ul)) & 255; } else throw new Error('Unsupported PNG filter'); } pixels.set(row, y * width); previous = row; }
  return { type: 'png', width, height, palette, pixels, dirty: false };
}
async function encodePng(image) { const rows = new Uint8Array((image.width + 1) * image.height); for (let y = 0; y < image.height; y++) rows.set(image.pixels.slice(y * image.width, (y + 1) * image.width), y * (image.width + 1) + 1); const pal = new Uint8Array(image.palette.flatMap(c => [parseInt(c.slice(1, 3), 16), parseInt(c.slice(3, 5), 16), parseInt(c.slice(5, 7), 16)])); const header = new Uint8Array(13); const v = new DataView(header.buffer); v.setUint32(0, image.width); v.setUint32(4, image.height); header.set([8, 3, 0, 0, 0], 8); return concat([new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10]), chunk('IHDR', header), chunk('PLTE', pal), chunk('IDAT', await deflate(rows)), chunk('IEND', new Uint8Array())]); }
async function localFile(path, create = false) { let folder = state.localRoot; const bits = path.split('/'); for (const bit of bits.slice(0, -1)) folder = await folder.getDirectoryHandle(bit, { create }); return folder.getFileHandle(bits.at(-1), { create }); }
async function readPath(path) { if (state.files.has(path)) return state.files.get(path); const buffer = state.localRoot ? await (await localFile(path)).getFile().then(f => f.arrayBuffer()) : await fetch(path).then(r => { if (!r.ok) throw new Error(`Could not load ${path}`); return r.arrayBuffer(); }); const file = path.endsWith('.png') ? await decodePng(buffer) : path.endsWith('.json') ? { type: 'json', value: JSON.parse(decode.decode(buffer)), dirty: false } : { type: 'text', value: decode.decode(buffer), dirty: false }; state.files.set(path, file); return file; }
async function savePath(path) { const file = state.files.get(path); if (!file) return; const bytes = file.type === 'png' ? await encodePng(file) : text.encode(file.type === 'json' ? `${JSON.stringify(file.value, null, 2)}\n` : file.value); if (state.localRoot) { const w = await (await localFile(path, true)).createWritable(); await w.write(bytes); await w.close(); file.dirty = false; status.textContent = `Saved ${path}`; } else { const a = el('a', { href: URL.createObjectURL(new Blob([bytes])), download: path.split('/').at(-1) }); a.click(); URL.revokeObjectURL(a.href); status.textContent = `Downloaded ${path}`; } }
const dirty = path => { state.files.get(path).dirty = true; state.activePath = path; };
const ctx = (canvas, width, height) => { canvas.width = width; canvas.height = height; return canvas.getContext('2d', { alpha: false }); };
const point = (event, canvas, width, height) => { const r = canvas.getBoundingClientRect(); return [Math.max(0, Math.min(width - 1, Math.floor((event.clientX - r.left) * width / r.width))), Math.max(0, Math.min(height - 1, Math.floor((event.clientY - r.top) * height / r.height)))]; };
function palettePicker(value, change) { const wrap = el('div', { class: 'palette' }); PALETTE.forEach((color, index) => wrap.append(el('button', { type: 'button', class: `swatch ${value === index ? 'active' : ''}`, title: `${index}: ${color}`, style: `background:${color}`, onclick: () => change(index) }))); return wrap; }
function select(label, choices, value, change) { return el('label', {}, [label, el('select', { onchange: e => change(e.target.value) }, choices.map(([id, name]) => el('option', { value: id, ...(id === value ? { selected: '' } : {}) }, [name]))) ]); }
function shell(editor, inspector, content) { const root = el('section', { class: 'editor' }); root.append(el('aside', { class: 'inspector' }, [el('h1', {}, [editor.label]), inspector]), el('section', { class: 'canvas-panel' }, content)); app.replaceChildren(root); app.focus(); }
function tile(image, cell) { const row = Math.floor(cell / 40), column = cell % 40, mask = new Uint8Array(8), colors = new Set(); for (let y = 0; y < 8; y++) for (let x = 0; x < 8; x++) { const value = image.pixels[(row * 8 + y) * 320 + column * 8 + x]; if (value) { mask[y] |= 0x80 >> x; colors.add(value); } } return { mask, color: colors.size ? [...colors][0] : 0 }; }
function applyTile(image, cell, mask, color) { const row = Math.floor(cell / 40), column = cell % 40; for (let y = 0; y < 8; y++) for (let x = 0; x < 8; x++) image.pixels[(row * 8 + y) * 320 + column * 8 + x] = mask[y] & (0x80 >> x) ? color : 0; }
function key(mask) { return [...mask].join(','); }
function charsetFrom(images, stable = null) { const glyphs = stable ? stable.map(mask => new Uint8Array(mask)) : [new Uint8Array(8)], ids = new Map([[key(glyphs[0]), 0]]); glyphs.forEach((mask, index) => { if (!ids.has(key(mask))) ids.set(key(mask), index); }); const model = { glyphs, ids, stable: Boolean(stable), spares: stable ? glyphs.map((mask, index) => ids.get(key(mask)) === index ? null : index).filter(index => index !== null) : [] }, maps = new Map(); for (const [name, image] of images) maps.set(name, mapFromImage(image, model, true)); return { ...model, maps }; }
function mapFromImage(image, model, add = false) { const screen = new Uint8Array(1000), color = new Uint8Array(1000); for (let cell = 0; cell < 1000; cell++) { const value = tile(image, cell), k = key(value.mask); if (!model.ids.has(k)) { if (!add) throw new Error('The selected image uses a glyph outside this shared charset.'); if (model.stable) { const slot = model.spares.shift(); if (slot === undefined) throw new Error('Shared charset has no free stable glyph IDs. Reduce unique glyphs or split screens into another charset group.'); model.ids.set(k, slot); model.glyphs[slot] = value.mask; } else { if (model.glyphs.length === 256) throw new Error('Shared charset needs more than 256 glyphs. Reduce the screens that share it or reduce unique glyphs.'); model.ids.set(k, model.glyphs.length); model.glyphs.push(value.mask); } } screen[cell] = model.ids.get(k); color[cell] = value.color; } return { screen, color }; }
function titleImage(base, selection, stateName) { const out = { ...base, pixels: new Uint8Array(base.pixels) }; if (!selection) return out; const [markerColumn, markerRow] = selection.marker.source_cell, row = selection.states[stateName].row, marker = tile(base, markerRow * 40 + markerColumn); applyTile(out, markerRow * 40 + markerColumn, new Uint8Array(8), 0); applyTile(out, row * 40 + markerColumn, marker.mask, marker.color); Object.entries(selection.states).forEach(([name, item]) => { for (let column = item.text_start_column; column < item.text_start_column + item.text_width; column++) { const cell = item.row * 40 + column, value = tile(out, cell); if (value.color) applyTile(out, cell, value.mask, name === stateName ? selection.highlight.active_color : selection.highlight.inactive_color); } }); return out; }
async function characterSources() { const charset = state.manifest.charsets[0], images = await Promise.all(charset.sources.map(readPath)); const order = charset.id_order ? (await readPath(charset.id_order)).value.glyph_masks_hex.map(mask => Uint8Array.from(mask.match(/../g).map(byte => parseInt(byte, 16))) ) : null; return { paths: charset.sources, images, charset: charsetFrom(charset.sources.map((path, index) => [path, images[index]]), order) }; }
function drawGlyph(context, glyphs, glyph, x, y, color, scale = 1) { context.fillStyle = PALETTE[color]; const mask = glyphs[glyph]; for (let py = 0; py < 8; py++) for (let px = 0; px < 8; px++) if (mask[py] & (0x80 >> px)) context.fillRect(x + px * scale, y + py * scale, scale, scale); }
function drawScreen(canvas, model, map, scale = 1) { const c = ctx(canvas, 320 * scale, 200 * scale); c.fillStyle = PALETTE[0]; c.fillRect(0, 0, canvas.width, canvas.height); for (let cell = 0; cell < 1000; cell++) drawGlyph(c, model.glyphs, map.screen[cell], (cell % 40) * 8 * scale, Math.floor(cell / 40) * 8 * scale, map.color[cell], scale); }
function drawBitmap(canvas, selectors, high, low, ram, scale = 1, overlay = []) { const c = ctx(canvas, 320 * scale, 200 * scale); for (let y = 0; y < 200; y++) for (let x = 0; x < 160; x++) { const cell = Math.floor(y / 8) * 40 + Math.floor(x / 4), color = [0, high.pixels[cell], low.pixels[cell], ram.pixels[cell]][selectors.pixels[y * 160 + x]]; c.fillStyle = PALETTE[color]; c.fillRect(x * 2 * scale, y * scale, 2 * scale, scale); } c.strokeStyle = PALETTE[7]; c.lineWidth = scale; overlay.forEach(([x, y, w, h, label]) => { c.strokeRect(x * 2 * scale, y * scale, w * 2 * scale, h * scale); c.fillStyle = PALETTE[1]; c.fillText(label, x * 2 * scale + 2, y * scale + 10); }); }
function navRender() { nav.replaceChildren(...state.manifest.editors.map(editor => el('a', { href: `#${editor.id}`, class: location.hash.slice(1) === editor.id ? 'active' : '' }, [editor.label]))); }
async function glyphEditor(editor) { const sources = await characterSources(), model = sources.charset, atlas = el('canvas'), detail = el('canvas'), count = el('p', { class: 'counter' }); const redraw = () => { const c = ctx(atlas, 512, 512); c.fillStyle = PALETTE[0]; c.fillRect(0, 0, 512, 512); for (let glyph = 0; glyph < model.glyphs.length; glyph++) { drawGlyph(c, model.glyphs, glyph, glyph % 16 * 32, Math.floor(glyph / 16) * 32, 1, 4); if (glyph === state.glyph) { c.strokeStyle = PALETTE[7]; c.strokeRect(glyph % 16 * 32, Math.floor(glyph / 16) * 32, 32, 32); } } const d = ctx(detail, 256, 256); d.fillStyle = PALETTE[0]; d.fillRect(0, 0, 256, 256); drawGlyph(d, model.glyphs, state.glyph, 0, 0, 1, 32); const uses = [...model.maps.values()].reduce((n, map) => n + [...map.screen].filter(value => value === state.glyph).length, 0); count.textContent = `Glyph ${state.glyph} is used ${uses} times across ${sources.paths.map(path => path.split('/').slice(-2, -1)[0]).join(' and ')}.`; };
  atlas.onclick = e => { const [x, y] = point(e, atlas, 512, 512); state.glyph = Math.min(model.glyphs.length - 1, Math.floor(y / 32) * 16 + Math.floor(x / 32)); redraw(); };
  detail.onclick = e => { const [x, y] = point(e, detail, 256, 256), updated = new Uint8Array(model.glyphs[state.glyph]); updated[Math.floor(y / 32)] ^= 0x80 >> Math.floor(x / 32); const original = key(model.glyphs[state.glyph]); sources.images.forEach((image, index) => { for (let cell = 0; cell < 1000; cell++) { const value = tile(image, cell); if (key(value.mask) === original) applyTile(image, cell, updated, value.color || 1); } dirty(sources.paths[index]); }); model.glyphs[state.glyph] = updated; redraw(); };
  shell(editor, [el('p', { class: 'help' }, ['This atlas is derived from the editable title and INFO images. Click a glyph, then edit its pixels; every matching source-image cell updates.']), count], [el('div', { class: 'glyph-layout' }, [atlas, el('div', { class: 'glyph-detail' }, [detail, el('p', { class: 'legend' }, ['The 256-slot limit applies to this shared image group.'])])])]); state.activePath = sources.paths[0]; redraw(); }
async function screenEditor(editor) { const image = await readPath(editor.image), selection = editor.selection ? (await readPath(editor.selection)).value : null, canvas = el('canvas'), glyphInput = el('input', { type: 'number', min: '0', value: '0' }); let selectedState = 'one'; const selected = el('p', { class: 'counter' }); const redraw = async () => { const sources = await characterSources(), visual = editor.id === 'title' ? titleImage(image, selection, selectedState) : image, model = sources.charset, map = mapFromImage(visual, model); drawScreen(canvas, model, map); }; canvas.onclick = async event => { const [x, y] = point(event, canvas, 320, 200), cell = Math.floor(y / 8) * 40 + Math.floor(x / 8), sources = await characterSources(), model = sources.charset, visible = editor.id === 'title' ? titleImage(image, selection, selectedState) : image, map = mapFromImage(visible, model); selected.textContent = `Cell ${cell} · row ${Math.floor(cell / 40)}, column ${cell % 40} · glyph ${map.screen[cell]} · color ${map.color[cell]}`; const current = tile(image, cell); if (event.shiftKey) applyTile(image, cell, current.mask, state.color); else { const glyph = Math.max(0, Math.min(model.glyphs.length - 1, Number(glyphInput.value))); applyTile(image, cell, model.glyphs[glyph], current.color || state.color); } dirty(editor.image); await redraw(); };
  const inspector = [el('p', { class: 'help' }, ['Click an 8×8 cell to apply a derived glyph. Shift-click changes its foreground color. The image is authoritative; glyph maps and atlas are rebuilt.']), glyphInput, el('h2', {}, ['Cell color']), palettePicker(state.color, value => { state.color = value; redraw(); }), selected]; if (selection) inspector.splice(1, 0, select('Preview selection', [['one', 'One Player'], ['two', 'Two Player'], ['auto', 'AI vs AI']], selectedState, value => { selectedState = value; redraw(); })); shell(editor, inspector, [el('div', { class: 'canvas-toolbar' }, [el('strong', {}, ['40 × 25 image-derived character screen']), el('span', { class: 'legend' }, ['Click: glyph · Shift-click: color'])]), canvas]); state.activePath = editor.image; await redraw(); }
async function bitmapEditor(editor) { const [selectors, high, low, ram, layout] = await Promise.all([readPath(editor.selectors), readPath(editor.screen_high), readPath(editor.screen_low), readPath(editor.color_ram), readPath(editor.layout)]); const canvas = el('canvas'); let mode = 'selector', slot = 1; const redraw = () => drawBitmap(canvas, selectors, high, low, ram, 2, Object.entries(layout.value.cell_rectangles).map(([id, value]) => [...value.logical_xywh, id.toUpperCase()])); canvas.onclick = e => { const [px, y] = point(e, canvas, 640, 400), x = Math.floor(px / 4), cell = Math.floor(y / 8) * 40 + Math.floor(x / 4); if (mode === 'selector') { selectors.pixels[y * 160 + x] = state.selector; dirty(editor.selectors); } else { [null, high, low, ram][slot].pixels[cell] = state.color; dirty([null, editor.screen_high, editor.screen_low, editor.color_ram][slot]); } redraw(); }; shell(editor, [el('p', { class: 'help' }, ['The board uses 160×200 logical pixels. Selector mode paints 00/01/10/11; local-color mode changes the selected 4×8 cell color slot.']), select('Edit mode', [['selector', '2-bit selector'], ['color', 'Local cell color']], mode, value => { mode = value; redraw(); }), select('Selector / local slot', [['0', '00 background'], ['1', '01 screen high'], ['2', '10 screen low'], ['3', '11 Color RAM']], String(slot), value => { slot = Number(value); state.selector = slot; redraw(); }), el('h2', {}, ['Color']), palettePicker(state.color, value => { state.color = value; redraw(); })], [el('div', { class: 'canvas-toolbar' }, [el('strong', {}, ['160 × 200 logical-pixel board'])]), canvas]); state.activePath = editor.selectors; redraw(); }
async function markEditor(editor) { const picker = el('select'); editor.marks.forEach(mark => picker.append(el('option', { value: mark.id }, [mark.id.toUpperCase()]))); let current = editor.marks[0]; const canvas = el('canvas'), message = el('p', { class: 'mark-preview' }); const redraw = async () => { const image = await readPath(current.path), c = ctx(canvas, image.width * 32, image.height * 32); for (let y = 0; y < image.height; y++) for (let x = 0; x < image.width; x++) { c.fillStyle = PALETTE[image.pixels[y * image.width + x]]; c.fillRect(x * 32, y * 32, 32, 32); c.strokeStyle = '#333'; c.strokeRect(x * 32, y * 32, 32, 32); } message.textContent = `${current.id.toUpperCase()} is ${image.width}×${image.height} logical multicolor pixels.`; state.activePath = current.path; }; canvas.onclick = async e => { const image = await readPath(current.path), [x, y] = point(e, canvas, canvas.width, canvas.height); image.pixels[Math.floor(y / 32) * image.width + Math.floor(x / 32)] = state.color; dirty(current.path); redraw(); }; picker.onchange = async e => { current = editor.marks.find(mark => mark.id === e.target.value); redraw(); }; shell(editor, [el('p', { class: 'help' }, ['Click a 2×1 logical pixel to set its native C64 color.']), el('label', {}, ['Mark', picker]), el('h2', {}, ['Paint color']), palettePicker(state.color, value => { state.color = value; redraw(); })], [el('div', { class: 'mark-layout' }, [canvas, message])]); await redraw(); }
function markdownLines(markdown, width) { return markdown.split('\n').flatMap(line => { const words = line.replace(/^#{1,6}\s*/, '').replace(/^[-*]\s+/, '• ').replace(/[*`|]/g, '').trim().split(/\s+/).filter(Boolean), rows = []; let row = ''; words.forEach(word => { if (`${row} ${word}`.trim().length > width) { rows.push(row); row = word; } else row = `${row} ${word}`.trim(); }); return rows.length || row ? [...rows, row] : ['']; }); }
async function markdownEditor(editor) { const archive = await readPath(editor.path), info = state.manifest.editors.find(item => item.id === 'info'), image = await readPath(info.image), textarea = el('textarea', {}, [archive.value]), scroll = el('input', { type: 'number', min: '0', value: '0' }), canvas = el('canvas'); const code = char => { const c = char.toUpperCase(); return c >= 'A' && c <= 'Z' ? c.charCodeAt(0) - 64 : c >= '0' && c <= '9' ? c.charCodeAt(0) - 21 : ({ ' ': 0, '?': 37, ':': 38, '.': 39, ',': 40, '/': 41, '-': 42, '!': 43, '(': 45, ')': 46 }).at(c) ?? 0; }; const redraw = async () => { const sources = await characterSources(), map = sources.charset.maps.get(info.image); drawScreen(canvas, sources.charset, map, 2); const c = canvas.getContext('2d'), lines = markdownLines(textarea.value, editor.viewport[0]), start = Math.min(Number(scroll.value), Math.max(0, lines.length - editor.viewport[1])); scroll.max = Math.max(0, lines.length - editor.viewport[1]); for (let y = 0; y < editor.viewport[1]; y++) for (let x = 0; x < editor.viewport[0]; x++) { c.fillStyle = PALETTE[0]; c.fillRect((5 + x) * 16, (4 + y) * 16, 16, 16); const glyph = code((lines[start + y] ?? '')[x] ?? ' '); drawGlyph(c, sources.charset.glyphs, glyph, (5 + x) * 16, (4 + y) * 16, 1, 2); } }; textarea.oninput = () => { archive.value = textarea.value; dirty(editor.path); redraw(); }; scroll.oninput = redraw; shell(editor, [el('p', { class: 'help' }, ['A 29×18 browser preview. The compiler remains the final runtime authority.']), el('label', {}, ['Scroll row', scroll])], [el('div', { class: 'markdown-layout' }, [textarea, canvas])]); state.activePath = editor.path; await redraw(); }
async function layoutEditor(editor) { const boardPath = editor.paths.find(path => path.endsWith('layout.json')), board = await readPath(boardPath), textarea = el('textarea'), canvas = el('canvas'), picker = el('select'); [['board', 'Board mark rectangles'], ['info', 'INFO text viewport'], ['title', 'Title selection rows']].forEach(([id, label]) => picker.append(el('option', { value: id }, [label]))); let kind = 'board'; const data = () => kind === 'board' ? board.value : state.manifest.layouts[kind === 'info' ? 'info-text' : 'title-selection']; const redraw = async () => { textarea.value = JSON.stringify(data(), null, 2); const c = ctx(canvas, 640, 400); c.fillStyle = PALETTE[0]; c.fillRect(0, 0, 640, 400); if (kind === 'board') { const e = state.manifest.editors.find(item => item.id === 'board'), [s, h, l, r] = await Promise.all([readPath(e.selectors), readPath(e.screen_high), readPath(e.screen_low), readPath(e.color_ram)]); drawBitmap(canvas, s, h, l, r, 2, Object.entries(board.value.cell_rectangles).map(([id, value]) => [...value.logical_xywh, id.toUpperCase()])); } else { c.fillStyle = PALETTE[4]; c.fillRect(0, 0, 640, 400); c.strokeStyle = PALETTE[7]; const value = data(); if (kind === 'info') c.strokeRect(value.x * 16, value.y * 16, value.width * 16, value.height * 16); else value.rows.forEach(row => c.strokeRect(value.text_x * 16, row * 16, 20 * 16, 16)); } }; picker.onchange = e => { kind = e.target.value; redraw(); }; textarea.onchange = () => { try { const value = JSON.parse(textarea.value); if (kind === 'board') { board.value = value; dirty(boardPath); } else { state.manifest.layouts[kind === 'info' ? 'info-text' : 'title-selection'] = value; state.files.set(manifestPath, { type: 'json', value: state.manifest, dirty: true }); state.activePath = manifestPath; } redraw(); } catch (error) { alert(`Invalid JSON: ${error.message}`); } }; shell(editor, [el('p', { class: 'help' }, ['Edit board rectangles, INFO viewport geometry, and title-selection rows.']), el('label', {}, ['Layout', picker])], [el('div', { class: 'layout-layout' }, [textarea, canvas])]); await redraw(); }
async function home() { const fragment = homeTemplate.content.cloneNode(true), cards = fragment.querySelector('#home-cards'); const notes = { 'glyph-atlas': 'Derived 8×8 glyph viewer/editor with shared usage.', 'petscii-screen': 'Edit a 40×25 source image; maps are rebuilt.', 'multicolor-bitmap': 'Edit selectors and local colors.', mark: 'Paint logical multicolor mark pixels.', markdown: 'Edit INFO text with C64 viewport preview.', layout: 'Move text, title, and mark geometry.' }; state.manifest.editors.forEach(editor => cards.append(el('a', { href: `#${editor.id}` }, [el('strong', {}, [editor.label]), el('small', {}, [notes[editor.kind]])]))); app.replaceChildren(fragment); }
async function route() { try { navRender(); const id = location.hash.slice(1); if (!id) return home(); const editor = state.manifest.editors.find(item => item.id === id); if (!editor) return home(); if (editor.kind === 'glyph-atlas') return glyphEditor(editor); if (editor.kind === 'petscii-screen') return screenEditor(editor); if (editor.kind === 'multicolor-bitmap') return bitmapEditor(editor); if (editor.kind === 'mark') return markEditor(editor); if (editor.kind === 'markdown') return markdownEditor(editor); return layoutEditor(editor); } catch (error) { console.error(error); app.replaceChildren(el('section', { class: 'notice' }, [`Editor error: ${error.message}`])); } }
async function openLocal() { if (!window.showDirectoryPicker) return alert('Use a Chromium-family browser for local directory writes, or download the active file.'); try { state.localRoot = await window.showDirectoryPicker({ mode: 'readwrite' }); state.files.clear(); state.manifest = (await readPath(manifestPath)).value; PALETTE = state.manifest.palette.colors; status.textContent = `Local project: ${state.localRoot.name}`; route(); } catch (error) { if (error.name !== 'AbortError') alert(error.message); } }
async function boot() { state.manifest = (await readPath(manifestPath)).value; PALETTE = state.manifest.palette.colors; navRender(); route(); }
window.addEventListener('hashchange', route); $('#open-local').onclick = openLocal; $('#download-active').onclick = () => savePath(state.activePath); boot();
